services:
  - type: web
    name: whale-tracker-pro
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api.whales:app"
    envVars:
      - key: MARKETDATA_API_KEY
        sync: false
    plan: free
